//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShop.@base
{
    using System;
    using System.IO;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Article { get; set; }
        public int CategoryID { get; set; }
        public int SizeID { get; set; }
        public int ProviderID { get; set; }
        public string Description { get; set; }
        public string ProductName { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Size Size { get; set; }

        public string correctimage
        {
            get
            {
                string path = Path.Combine(Directory.GetParent(Path.Combine(Directory.GetParent(Directory.GetCurrentDirectory()).FullName)).FullName, @"Images\");
                if (String.IsNullOrEmpty(Image) || String.IsNullOrWhiteSpace(Image) || Image == null)
                {
                    return path + "default.jpg";
                }
                else
                {
                    return path + Image;
                }
            }
        }
    }

}
